# Generated by Django 3.1.5 on 2021-02-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebappBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
