# Generated by Django 3.1.5 on 2021-02-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebappBackend', '0003_quiz_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='questions',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
